In [8]:
import numpy as np
import sys

In [ ]:
n = int(input('Jumlah variabel SPL '))


Jumlah variabel SPL 3


In [ ]:
a = np.zeros((n,n+1))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
print('isikan koefisien variabel masing2 :')
for i in range(n):
  for j in range(n+1):
    a[i][j]=float(input('a['+str(i)+']['+str(j)+']'))



isikan koefisien variabel masing2 :
a[0][0]1
a[0][1]2
a[0][2]3
a[0][3]4
a[1][0]4
a[1][1]3
a[1][2]2
a[1][3]3
a[2][0]2
a[2][1]3
a[2][2]3
a[2][3]3


In [ ]:
print(a)

[[1. 2. 3. 4.]
 [4. 3. 2. 3.]
 [2. 3. 3. 3.]]


In [ ]:
for i in range(n):
  if a[i][i]==0.0 :
    sys.exit('pembagi 0')

  for j in range(i+1,n):
    rasio = a[j][i]/a[i][j]
    for k in range(n+1):
      a[j][k] = a[j][k] - rasio*a[i][k]


In [ ]:
x